#ifndef COMMANDTYPES_HPP
#define COMMANDTYPES_HPP

enum ErrorCodes
{
    NOT_REGISTERED = 10,
    INVALID_FORMAT = 11
};

enum GeneralDeviceCommands
{
    HEARTBEAT = 20,
    REGISTRATION = 21,
    DEVICE_INFO = 22
};

enum DeviceStatus
{
    CONNECTED = 30,
    UNSTABLE = 31,
    DISCONNECTED = 32
};

enum BedCommands
{
    BED_BUTTON_PRESSED = 40,
    BED_LED_ON = 41,
    BED_PRESSURE_SENSOR_VALUE = 42
};

enum ChairCommands
{
    CHAIR_BUTTON_PRESSED = 50,
    CHAIR_LED_ON = 51,
    CHAIR_VIBRATOR_ON = 52,
    CHAIR_PRESSURE_SENSOR_VALUE = 53
};

enum ColumnCommands
{
    COLUMN_BUTTON_PRESSED = 60,
    COLUMN_LED_ON = 61,
    COLUMN_BUZZER_ON = 62,
    COLUMN_SMOKE_SENSOR_VALUE = 63
};

enum DoorCommands
{
    DOOR_BUTTON_INSIDE_PRESSED = 70,
    DOOR_BUTTON_OUTSIDE_PRESSED = 71,
    DOOR_LED_INSIDE_ON = 72,
    DOOR_LED_OUTSIDE_ON = 73,
    DOOR_DOOR_OPEN = 74,
    DOOR_DOOR_LOCKED = 75
};

enum FridgeCommands
{
    FRIDGE_DOOR_CLOSED = 80,
    FRIDGE_FAN_ON = 81,
    FRIDGE_RAW_TEMPERATURE_SENSOR_INSIDE_VALUE = 82,
    FRIDGE_RAW_TEMPERATURE_SENSOR_OUTSIDE_VALUE = 83,
    FRIDGE_COOLER_ON = 84,
    FRIDGE_REQUESTED_FRIDGE_TEMPERATURE = 85,
    FRIDGE_DOOR_OPEN_COUNTER = 86,
    FRIDGE_TEMPERATURE_INSIDE_VALUE = 87
};

enum LampCommands
{
    LAMP_MOVEMENT_DETECTED = 90,
    LAMP_LED_VALUE = 91,
    LAMP_LED_ON = 92
};

enum SimulatedDeviceCommands
{
    SIMULATED_BUTTON1_PRESSED = 100,
    SIMULATED_BUTTON2_PRESSED = 101,
    SIMULATED_LED1_VALUE = 102,
    SIMULATED_LED2_VALUE = 103,
    SIMULATED_LED3_VALUE = 104,
    SIMULATED_DIMMER_VALUE = 105
};

enum WallCommands
{
    WALL_CURTAIN_OPEN = 110,
    WALL_LEDSTRIP_ON = 111,
    WALL_DIMMER_VALUE = 112,
    WALL_LDR_VALUE = 113
};

enum WebsiteCommands
{
    WEBSITE_UPDATE = 120,
    WEBSITE_FORWARD = 121
};

enum WIBCommands
{
    WIB_SWITCH_ON = 130,
    WIB_LED_ON = 131,
    WIB_DIMMER_VALUE = 132
};

#endif